### ISSUE TITLE
Farsi Interface should user rtl direction

### ISSUE THREAD

**Issue by reza1615** [huggle/huggle3-qt-lx#256] opened 2017-10-23 10:58 UTC
Farsi Interface at Haggle 3.3.2 is left to right which should be right to left like Arabic
please solve it. In my opinion, somewhere Farsi setting missed rtl.

screenshot of Farsi interface
![image](https://user-images.githubusercontent.com/2202483/31885691-4247d5a6-b7fe-11e7-9699-fc92edfc1534.png)

screenshot of Arabic interface
![image](https://user-images.githubusercontent.com/2202483/31885620-f953c7ba-b7fd-11e7-9f4e-5283a522a216.png)

**Comment by benapetr** [comment] 2017-10-23 11:32
there is special keyword in localization file called "isrtl" which must be either true or false, for some reason it is now:

```
<string name="isrtl">Ù~FØ§ØµØ­Û~LØ­</string>
```

I don't know what that is, but it's wrong, it needs to be fixed on translate wiki

**Closed by benapetr** 2017-10-23 11:32 UTC

**Comment by Ladsgroup** [comment] 2017-10-25 16:17
@benapetr Hey, Do you have some time to look into this?

**Comment by benapetr** [comment] 2017-10-26 09:12
@Ladsgroup as I already said in previous comment, the problem is not in Huggle, the problem is on TWN, someone screwed the localization magic key "isrtl". It needs to be set to "true" instead of "Ù~FØ§ØµØ­Û~LØ­"

**Comment by benapetr** [comment] 2017-10-26 09:35
I even see that someone fixed this on TWN already but it wasn't pushed to our repo from there yet
