### ISSUE TITLE
Decide whether to use Phabricator or GitHub Issues for issue tracking

### ISSUE THREAD

**Issue by NovemLinguae** [huggle/huggle3-qt-lx#357] opened 2023-02-17 20:19 UTC
I just discovered the Huggle tag on phabricator today, and it has about [100 open issues](https://phabricator.wikimedia.org/maniphest/?project=PHID-PROJ-qyafdxss7d5gtft2xgh3&statuses=open()&group=none&order=newest#R) and [a kanban board](https://phabricator.wikimedia.org/project/board/520/).

But we also have the GitHub Issues tab for this repository.

Might make more sense to pick one or the other, so things aren't spread out everywhere.

I'd suggest turning off the Issues tab for this repository, and adding a note to the readme to use Phabricator.

**Comment by phuzion** [comment] 2023-02-17 20:23
Dupe of #325

**Closed** 2023-02-17 20:24 UTC
